[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'raw1z/vim-csharp'

[[plugins]]
repo = 'simpsonjulian/cypher-vim-syntax'

[[plugins]]
repo = 'raw1z/Windows-PowerShell-Syntax-Plugin'

[[plugins]]
repo = 'vim-scripts/Vim-R-plugin'


